### ISSUE TITLE
Foute rendering in IE 11

### ISSUE THREAD

**Issue by timothy-debock** [milieuinfo/webcomponent-vl-ui-grid#7]
In internet explore 11 worden de elementen op de volledige breedte onder elkaar getoond

De originele componenten van webuniversum worden wel correct gerenderd

https://overheid.vlaanderen.be/webuniversum/v3/documentation/grid

**Comment by coemans** [comment]
Voorlopig worden alleen de evergreen browser ondersteund (beslissing TAW) met uitzondering van Edge waar we besloten hebben om de volgende release af te wachten waar shadow DOM ondersteuning toegevoegd wordt cfr. UIG-87.

Als er echt nood is aan IE11 ondersteuning, zou dit in principe toegevoegd kunnen worden.
